import { useAuth0 } from "@auth0/auth0-react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const {
    user,
    isLoading,
    isAuthenticated,
    getAccessTokenSilently,
    error,
    getIdTokenClaims,
  } = useAuth0();

  useEffect(() => {
    getIdTokenClaims().then(console.log);
    getAccessTokenSilently({}).then(console.log);
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>User Information:</h1>
        {JSON.stringify(user)}
      </main>
    </div>
  );
};

export default Home;
